{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x-form-backend.fullname" $ }}-{{ $serviceConfig.name }}
  labels:
    {{- include "x-form-backend.serviceLabels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "serviceName" $serviceConfig.name) | nindent 4 }}
spec:
  replicas: {{ $serviceConfig.replicaCount | default $.Values.replicaCount }}
  strategy:
    {{- toYaml $.Values.deploymentStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "x-form-backend.serviceSelectorLabels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "serviceName" $serviceConfig.name) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml $.Values.podAnnotations | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "x-form-backend.serviceSelectorLabels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values "serviceName" $serviceConfig.name) | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "x-form-backend.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $serviceConfig.name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: {{ include "x-form-backend.serviceImage" (dict "Values" $.Values "serviceConfig" $serviceConfig "Chart" $.Chart) }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $serviceConfig.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            {{- include "x-form-backend.commonEnv" (dict "Values" $.Values "serviceName" $serviceConfig.name "Chart" $.Chart) | nindent 12 }}
            {{- range $key, $value := $serviceConfig.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PORT
              value: {{ $serviceConfig.port | quote }}
          {{- if $.Values.healthChecks.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ $.Values.healthChecks.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.healthChecks.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.healthChecks.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.healthChecks.livenessProbe.failureThreshold }}
            successThreshold: {{ $.Values.healthChecks.livenessProbe.successThreshold }}
          {{- end }}
          {{- if $.Values.healthChecks.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: {{ $.Values.healthChecks.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.healthChecks.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.healthChecks.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.healthChecks.readinessProbe.failureThreshold }}
            successThreshold: {{ $.Values.healthChecks.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml ($serviceConfig.resources | default $.Values.resources) | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "x-form-backend.fullname" $ }}-config
        - name: tmp
          emptyDir: {}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
