version: '3.8'

services:
  # PostgreSQL for users and forms
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: xform_db
      POSTGRES_USER: xform_user
      POSTGRES_PASSWORD: xform_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - xform-network

  # Redis for real-time features and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - xform-network

  # API Gateway (NGINX)
  api-gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - form-service
      - response-service
      - realtime-service
      - analytics-service
    networks:
      - xform-network

  # Auth Service (Node.js)
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=your-jwt-secret-key
      - POSTGRES_URL=postgresql://xform_user:xform_password@postgres:5432/xform_db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./services/auth-service:/app
    networks:
      - xform-network

  # Form Service (Go)
  form-service:
    build:
      context: ./services/form-service
      dockerfile: Dockerfile
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://xform_user:xform_password@postgres:5432/xform_db
      - JWT_SECRET=your-jwt-secret-key
      - REDIS_URL=redis://redis:6379
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/form-service:/app
    networks:
      - xform-network

  # Real-time Service (Go)
  realtime-service:
    build:
      context: ./services/realtime-service
      dockerfile: Dockerfile
    environment:
      - PORT=8002
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-key
    ports:
      - "8002:8002"
    depends_on:
      - redis
    volumes:
      - ./services/realtime-service:/app
    networks:
      - xform-network

  # Response Service (Node.js)
  response-service:
    build:
      context: ./services/response-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3002
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - JWT_SECRET=your-jwt-secret-key
    ports:
      - "3002:3002"
    volumes:
      - ./services/response-service:/app
    networks:
      - xform-network

  # Analytics Service (Python)
  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    environment:
      - PORT=5001
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - BIGQUERY_PROJECT_ID=${BIGQUERY_PROJECT_ID}
      - JWT_SECRET=your-jwt-secret-key
    ports:
      - "5001:5001"
    volumes:
      - ./services/analytics-service:/app
    networks:
      - xform-network

volumes:
  postgres_data:
  redis_data:

networks:
  xform-network:
    driver: bridge
