basePath: /
definitions:
  GatewayInfoResponse:
    properties:
      features:
        items:
          type: string
        type: array
      message:
        example: Enhanced X-Form API Gateway
        type: string
      path:
        example: /
        type: string
      version:
        example: 1.0.0
        type: string
    type: object
  HealthResponse:
    properties:
      services:
        additionalProperties:
          type: string
        type: object
      status:
        example: healthy
        type: string
      timestamp:
        example: "2025-09-12T01:35:03+08:00"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the enhanced X-Form Backend API Gateway with comprehensive
    features including parameter validation, whitelist validation, authentication,
    rate limiting, service discovery, request transformation, and reverse proxy
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Enhanced X-Form API Gateway
  version: 1.0.0
paths:
  /:
    get:
      consumes:
      - application/json
      description: Get comprehensive information about the Enhanced API Gateway including
        all implemented features
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GatewayInfoResponse'
      summary: Gateway Information
      tags:
      - info
  /api/v1/health:
    get:
      consumes:
      - application/json
      description: Get the health status of the API Gateway and all connected services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HealthResponse'
      summary: Health Check
      tags:
      - health
  /api/v1/metrics:
    get:
      consumes:
      - application/json
      description: Get comprehensive metrics from the API Gateway including request
        counts, latency, and service health
      produces:
      - text/plain
      responses:
        "200":
          description: Prometheus metrics format
          schema:
            type: string
      summary: Metrics
      tags:
      - monitoring
  /health:
    get:
      consumes:
      - application/json
      description: Get the health status of the API Gateway and all connected services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HealthResponse'
      summary: Health Check
      tags:
      - health
  /metrics:
    get:
      consumes:
      - application/json
      description: Get comprehensive metrics from the API Gateway including request
        counts, latency, and service health
      produces:
      - text/plain
      responses:
        "200":
          description: Prometheus metrics format
          schema:
            type: string
      summary: Metrics
      tags:
      - monitoring
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
