# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: xform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: xform/auth-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: NODE_ENV
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: JWT_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: GOOGLE_CLIENT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: xform
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001
---
# Form Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-service
  namespace: xform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: form-service
  template:
    metadata:
      labels:
        app: form-service
    spec:
      containers:
      - name: form-service
        image: xform/form-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: REDIS_URL
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: form-service
  namespace: xform
spec:
  selector:
    app: form-service
  ports:
  - port: 8001
    targetPort: 8001
---
# Response Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: response-service
  namespace: xform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: response-service
  template:
    metadata:
      labels:
        app: response-service
    spec:
      containers:
      - name: response-service
        image: xform/response-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: JWT_SECRET
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: FIREBASE_PROJECT_ID
        - name: FIREBASE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: FIREBASE_PRIVATE_KEY
        - name: FIREBASE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: FIREBASE_CLIENT_EMAIL
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: response-service
  namespace: xform
spec:
  selector:
    app: response-service
  ports:
  - port: 3002
    targetPort: 3002
---
# Analytics Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: xform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: xform/analytics-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: xform-config
              key: ENVIRONMENT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: JWT_SECRET
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: FIREBASE_PROJECT_ID
        - name: FIREBASE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: FIREBASE_PRIVATE_KEY
        - name: FIREBASE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: FIREBASE_CLIENT_EMAIL
        - name: BIGQUERY_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: xform-secrets
              key: BIGQUERY_PROJECT_ID
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: xform
spec:
  selector:
    app: analytics-service
  ports:
  - port: 5001
    targetPort: 5001
