# OpenTelemetry Collector Configuration
# This configuration receives OTLP traces and forwards them to Jaeger
# while also exposing metrics for Prometheus scraping

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  memory_limiter:
    limit_mib: 512
  
  resource:
    attributes:
      - key: collector.name
        value: otel-collector
        action: upsert
      - key: collector.version
        value: 0.88.0
        action: upsert

exporters:
  # Export traces to Jaeger
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  
  # Export to OTLP (for Grafana Tempo)
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  # Export metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      collector: otel-collector
  
  # Console exporter for debugging
  logging:
    loglevel: info
  
  # Export to external APM (optional)
  otlp/external:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [jaeger, otlp/tempo, logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, logging]
  
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
