version: "1.0.0"
environment: "development"

server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60
  timeout: 30

security:
  jwt:
    secret: "dev-secret-key-for-development-only-must-be-32-chars-minimum!"
    algorithm: "HS256"
    expiration_time: "24h"
    refresh_time: "168h"
    issuer: "api-gateway"
    audience: "users"

  whitelist:
    enabled: false
    allowed_ips: []
    blocked_ips: []
    trust_proxy: true
    proxy_header: "X-Forwarded-For"

  rate_limit:
    enabled: true
    rps: 100
    burst: 200
    window: "1m"

auth:
  service_url: "http://localhost:8001"
  timeout: "30s"
  retry_attempts: 3
  retry_delay: "1s"

services:
  discovery:
    type: "static"
    address: "localhost"
    timeout: "10s"
    interval: "30s"
  
  services:
    auth-service:
      name: "auth-service"
      url: "http://localhost:8001"
      health_check: "/health"
      timeout: "30s"
      retries: 3
    form-service:
      name: "form-service"
      url: "http://localhost:8002"
      health_check: "/health"
      timeout: "30s"
      retries: 3

proxy:
  timeout: "30s"
  keep_alive: "60s"

validation:
  enabled: true

log:
  level: "debug"
  format: "json"
  output: "stdout"

metrics:
  enabled: true
  port: "9090"
  path: "/metrics"
  namespace: "xform"
  interval: "30s"

cors:
  enabled: true
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
  exposed_headers: ["Content-Length", "Content-Type"]
  allow_credentials: true
  max_age: 86400

rate_limit:
  enabled: true
  rps: 100
  burst: 200
  window: "1m"